-- MySQL Script generated by MySQL Workbench
-- Tue Mar  3 20:47:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema b2b
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `b2b` ;

-- -----------------------------------------------------
-- Schema b2b
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `b2b` DEFAULT CHARACTER SET utf8 ;
USE `b2b` ;

-- -----------------------------------------------------
-- Table `b2b`.`goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`goods` ;

CREATE TABLE IF NOT EXISTS `b2b`.`goods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL COMMENT 'Наименование товара',
  `description` VARCHAR(45) NOT NULL COMMENT 'Описание товара',
  `total_weight` FLOAT NULL COMMENT 'БРУТТО',
  `net_weight` FLOAT NULL COMMENT 'НЕТТО',
  `volume` FLOAT NULL COMMENT 'Объём',
  `changed_at` DATETIME NOT NULL DEFAULT now() COMMENT 'Дата обновления',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2b`.`orders_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`orders_details` ;

CREATE TABLE IF NOT EXISTS `b2b`.`orders_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orders_head_id` INT NOT NULL COMMENT 'ссылка на заголовок заказа',
  `good_id` INT NOT NULL COMMENT 'Товар',
  `price` FLOAT NOT NULL COMMENT 'Цена',
  `qry` INT NOT NULL COMMENT 'Кол-во',
  `changed_at` DATETIME NOT NULL DEFAULT now() COMMENT 'Дата обновления',
  PRIMARY KEY (`id`),
  INDEX `fk_details_orders_goods1_idx` (`good_id` ASC),
  INDEX `fk_orders_details_orders_head1_idx` (`orders_head_id` ASC),
  CONSTRAINT `fk_details_orders_goods1`
    FOREIGN KEY (`good_id`)
    REFERENCES `b2b`.`goods` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_details_orders_head1`
    FOREIGN KEY (`orders_head_id`)
    REFERENCES `b2b`.`orders_head` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2b`.`orders_head`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`orders_head` ;

CREATE TABLE IF NOT EXISTS `b2b`.`orders_head` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL COMMENT 'Дата и время создания заказа',
  `trust_id` INT NOT NULL COMMENT 'Элемент доверия',
  `werehouse_id` INT NOT NULL COMMENT 'Склад\n',
  `price_id` INT NOT NULL COMMENT 'Тип цен',
  `changed_at` DATETIME NOT NULL DEFAULT now() COMMENT 'Дата обновления',
  PRIMARY KEY (`id`, `trust_id`),
  INDEX `fk_head_orders_trusts1_idx` (`trust_id` ASC),
  INDEX `fk_orders_head_prices1_idx` (`price_id` ASC),
  CONSTRAINT `fk_head_orders_trusts1`
    FOREIGN KEY (`trust_id`)
    REFERENCES `b2b`.`trust` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_head_prices1`
    FOREIGN KEY (`price_id`)
    REFERENCES `b2b`.`prices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2b`.`partners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`partners` ;

CREATE TABLE IF NOT EXISTS `b2b`.`partners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL COMMENT 'Полное наименование',
  `short_name` VARCHAR(45) NOT NULL COMMENT 'Короткое ноименование',
  `tin` VARCHAR(45) NOT NULL COMMENT 'ИНН',
  `phone` VARCHAR(100) NOT NULL,
  `addr` VARCHAR(100) NOT NULL,
  `changed_at` DATETIME NOT NULL DEFAULT now() COMMENT 'Дата обновления',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Таблица бизнес-партнёров';


-- -----------------------------------------------------
-- Table `b2b`.`price_lists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`price_lists` ;

CREATE TABLE IF NOT EXISTS `b2b`.`price_lists` (
  `price_id` INT NOT NULL COMMENT 'Тип цен',
  `good_id` INT NOT NULL COMMENT 'Товар',
  `price` FLOAT NOT NULL COMMENT 'Цена',
  `changed_at` DATETIME NOT NULL DEFAULT now() COMMENT 'Дата обновления',
  INDEX `fk_price_lists_goods1_idx` (`good_id` ASC),
  PRIMARY KEY (`good_id`, `price_id`),
  INDEX `fk_price_lists_prices1_idx` (`price_id` ASC),
  CONSTRAINT `fk_price_lists_goods1`
    FOREIGN KEY (`good_id`)
    REFERENCES `b2b`.`goods` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_price_lists_prices1`
    FOREIGN KEY (`price_id`)
    REFERENCES `b2b`.`prices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2b`.`price_type_relation_partners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`price_type_relation_partners` ;

CREATE TABLE IF NOT EXISTS `b2b`.`price_type_relation_partners` (
  `partner_id` INT NOT NULL COMMENT 'Партнёр',
  `price_id` INT NOT NULL COMMENT 'Тип цен\n',
  `changed_at` DATETIME NOT NULL DEFAULT now() COMMENT 'Дата обновления',
  PRIMARY KEY (`partner_id`, `price_id`),
  INDEX `fk_price_type_relation_partners_price_type1_idx` (`price_id` ASC),
  CONSTRAINT `fk_price_type_relation_partners_partners1`
    FOREIGN KEY (`partner_id`)
    REFERENCES `b2b`.`partners` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_price_type_relation_partners_price_type1`
    FOREIGN KEY (`price_id`)
    REFERENCES `b2b`.`prices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2b`.`prices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`prices` ;

CREATE TABLE IF NOT EXISTS `b2b`.`prices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'Наименование типа цен',
  `partner_id` INT NOT NULL COMMENT 'Партнёр',
  `changed_at` DATETIME NOT NULL DEFAULT now() COMMENT 'Дата обновления',
  INDEX `fk_price_type_partners1_idx` (`partner_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_price_type_partners1`
    FOREIGN KEY (`partner_id`)
    REFERENCES `b2b`.`partners` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2b`.`stocks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`stocks` ;

CREATE TABLE IF NOT EXISTS `b2b`.`stocks` (
  `warehouse_id` INT NOT NULL COMMENT 'Склад',
  `good_id` INT NOT NULL COMMENT 'Товар',
  `qty` INT NOT NULL COMMENT 'Кол-во',
  `changed_at` DATETIME NOT NULL DEFAULT now() COMMENT 'Дата обновления',
  INDEX `fk_stocks_warehouse1_idx` (`warehouse_id` ASC),
  INDEX `fk_stocks_goods1_idx` (`good_id` ASC),
  PRIMARY KEY (`warehouse_id`, `good_id`),
  CONSTRAINT `fk_stocks_warehouse1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `b2b`.`warehouse` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_stocks_goods1`
    FOREIGN KEY (`good_id`)
    REFERENCES `b2b`.`goods` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2b`.`trust`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`trust` ;

CREATE TABLE IF NOT EXISTS `b2b`.`trust` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_partner` INT NULL COMMENT 'Партнёр',
  `id_user` INT NOT NULL COMMENT 'Пользователь',
  `start_date` DATE NULL COMMENT 'Дата начала действия доверенности',
  `finish_date` DATE NULL COMMENT 'Действительно до',
  `changed_at` DATETIME NOT NULL DEFAULT now() COMMENT 'Дата обновления',
  PRIMARY KEY (`id`),
  INDEX `fk_trusts_users1_idx` (`id_user` ASC),
  INDEX `fk_trust_partners1_idx` (`id_partner` ASC),
  CONSTRAINT `fk_trusts_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `b2b`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_trust_partners1`
    FOREIGN KEY (`id_partner`)
    REFERENCES `b2b`.`partners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2b`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`users` ;

CREATE TABLE IF NOT EXISTS `b2b`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(20) NOT NULL COMMENT 'Имя',
  `surname` VARCHAR(45) NOT NULL COMMENT 'Фамилия',
  `tin` VARCHAR(45) NULL COMMENT 'ИНН',
  `phone` VARCHAR(20) NOT NULL,
  `birthday` DATE NOT NULL,
  `identity_card` VARCHAR(100) NOT NULL,
  `changed_at` DATETIME NOT NULL DEFAULT now() COMMENT 'Дата обновления',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Таблица бизнес-партнёров';


-- -----------------------------------------------------
-- Table `b2b`.`warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`warehouse` ;

CREATE TABLE IF NOT EXISTS `b2b`.`warehouse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'Наименование склада',
  `id_partner` INT NOT NULL COMMENT 'партнёр',
  `changed_at` DATETIME NOT NULL DEFAULT now() COMMENT 'Дата обновления',
  PRIMARY KEY (`id`),
  INDEX `fk_warehouse_partners1_idx` (`id_partner` ASC),
  CONSTRAINT `fk_warehouse_partners1`
    FOREIGN KEY (`id_partner`)
    REFERENCES `b2b`.`partners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
